<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\BuildingBlocks\BuildingBlocks.Observability\BuildingBlocks.Observability.csproj" />
    <ProjectReference Include="..\Modules\Audit\Modules.Audit.Infrastructure\Modules.Audit.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Authorization\Modules.Authorization.Application\Modules.Authorization.Application.csproj" />
    <ProjectReference Include="..\Modules\Authorization\Modules.Authorization.Infrastructure\Modules.Authorization.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Catalog\Modules.Catalog.Application\Modules.Catalog.Application.csproj" />
    <ProjectReference Include="..\Modules\Catalog\Modules.Catalog.Infrastructure\Modules.Catalog.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Companies\Modules.Companies.Application\Modules.Companies.Application.csproj" />
    <ProjectReference Include="..\Modules\Companies\Modules.Companies.Infrastructure\Modules.Companies.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Customers\Modules.Customers.Application\Modules.Customers.Application.csproj" />
    <ProjectReference Include="..\Modules\Customers\Modules.Customers.Infrastructure\Modules.Customers.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Geography\Modules.Geography.Application\Modules.Geography.Application.csproj" />
    <ProjectReference Include="..\Modules\Geography\Modules.Geography.Infrastructure\Modules.Geography.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Identity\Modules.Identity.Application\Modules.Identity.Application.csproj" />
    <ProjectReference Include="..\Modules\Identity\Modules.Identity.Infrastructure\Modules.Identity.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Notifications\Modules.Notifications.Infrastructure\Modules.Notifications.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Quotations\Modules.Quotations.Application\Modules.Quotations.Application.csproj" />
    <ProjectReference Include="..\Modules\Quotations\Modules.Quotations.Infrastructure\Modules.Quotations.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Storage\Modules.Storage.Application\Modules.Storage.Application.csproj" />
    <ProjectReference Include="..\Modules\Storage\Modules.Storage.Infrastructure\Modules.Storage.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Tenancy\Modules.Tenancy.Api\Modules.Tenancy.Api.csproj" />
    <ProjectReference Include="..\Modules\Tenancy\Modules.Tenancy.Application\Modules.Tenancy.Application.csproj" />
    <ProjectReference Include="..\Modules\Tenancy\Modules.Tenancy.Infrastructure\Modules.Tenancy.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
  </ItemGroup>
</Project>
