apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qep-data-protection-keys
  namespace: prod-qep-backend
  labels:
    app.kubernetes.io/name: qep-backend
    app.kubernetes.io/part-of: qep
    app.kubernetes.io/environment: prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
