// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modules.Messaging.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace Modules.Messaging.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MessagingDbContext))]
    partial class MessagingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Modules.Audit.Domain.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("action");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("actor_type");

                    b.Property<string>("ChangedFieldsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("changed_fields");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("outcome");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("resource_type");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "OccurredAt");

                    b.ToTable("entries", "audit", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Modules.Messaging.Domain.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("connection_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("LastActivityAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_at");

                    b.Property<DateTimeOffset?>("LastInboundAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_inbound_at");

                    b.Property<string>("LastInboundWamid")
                        .HasColumnType("text")
                        .HasColumnName("last_inbound_wamid");

                    b.Property<DateTimeOffset?>("LastMessageAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_message_at");

                    b.Property<short?>("LastMessageDirection")
                        .HasColumnType("smallint")
                        .HasColumnName("last_message_direction");

                    b.Property<Guid?>("LastMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_message_id");

                    b.Property<short?>("LastMessageKind")
                        .HasColumnType("smallint")
                        .HasColumnName("last_message_kind");

                    b.Property<string>("LastMessagePreview")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("last_message_preview");

                    b.Property<short?>("LastMessageStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("last_message_status");

                    b.Property<string>("ProfileName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("profile_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("UnreadCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("unread_count");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<string>("WaId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("wa_id");

                    b.HasKey("Id");

                    b.HasIndex("ProfileName")
                        .HasDatabaseName("IX_conversations_profile_name_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("ProfileName"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("ProfileName"), new[] { "gin_trgm_ops" });

                    b.HasIndex("WaId")
                        .HasDatabaseName("IX_conversations_wa_id_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("WaId"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("WaId"), new[] { "gin_trgm_ops" });

                    b.HasIndex("ConnectionId", "WaId")
                        .IsUnique()
                        .HasDatabaseName("IX_conversations_connection_wa");

                    b.HasIndex("TenantId", "Status", "LastActivityAt", "Id")
                        .IsDescending(false, false, true, true)
                        .HasDatabaseName("IX_conversations_tenant_status_activity");

                    b.HasIndex(new[] { "TenantId" }, "IX_conversations_tenant_open")
                        .HasFilter("status = 'Open'");

                    b.HasIndex(new[] { "TenantId" }, "IX_conversations_tenant_unread")
                        .HasFilter("unread_count > 0");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex(new[] { "TenantId" }, "IX_conversations_tenant_unread"), new[] { "UnreadCount" });

                    b.ToTable("conversations", "messaging", t =>
                        {
                            t.HasCheckConstraint("CK_conversations_status", "status IN ('Open','Resolved')");

                            t.HasCheckConstraint("CK_conversations_unread", "unread_count >= 0");
                        });
                });

            modelBuilder.Entity("Modules.Messaging.Infrastructure.Persistence.MessageMediaRecord", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempts");

                    b.Property<string>("FileName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("file_name");

                    b.Property<string>("LastError")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("last_error");

                    b.Property<string>("MetaMediaId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("meta_media_id");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("mime_type");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<string>("Sha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sha256");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StorageKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("storage_key");

                    b.Property<DateTimeOffset?>("StoredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("stored_at");

                    b.HasKey("MessageId");

                    b.HasIndex("NextAttemptAt")
                        .HasDatabaseName("IX_message_media_pending")
                        .HasFilter("stored_at IS NULL");

                    b.ToTable("message_media", "messaging");
                });

            modelBuilder.Entity("Modules.Messaging.Infrastructure.Persistence.MessageRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Caption")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("caption");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("connection_id");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Details")
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<short>("Direction")
                        .HasColumnType("smallint")
                        .HasColumnName("direction");

                    b.Property<int?>("FailureCode")
                        .HasColumnType("integer")
                        .HasColumnName("failure_code");

                    b.Property<string>("FailureTitle")
                        .HasColumnType("text")
                        .HasColumnName("failure_title");

                    b.Property<short>("Kind")
                        .HasColumnType("smallint")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector")
                        .HasComputedColumnSql("to_tsvector('messaging.es_unaccent', coalesce(text, '') || ' ' || coalesce(caption, ''))", true);

                    b.Property<Guid?>("SentByMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("sent_by_member_id");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Text")
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<string>("Wamid")
                        .HasColumnType("text")
                        .HasColumnName("wamid");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionId", "Wamid")
                        .IsUnique()
                        .HasDatabaseName("IX_messages_connection_wamid")
                        .HasFilter("wamid IS NOT NULL");

                    b.HasIndex("ConversationId", "ClientId")
                        .IsUnique()
                        .HasDatabaseName("IX_messages_conversation_client")
                        .HasFilter("client_id IS NOT NULL");

                    b.HasIndex("TenantId", "SearchVector")
                        .HasDatabaseName("IX_messages_tenant_search");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("TenantId", "SearchVector"), "gin");

                    b.HasIndex("ConversationId", "OccurredAt", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("IX_messages_thread");

                    b.ToTable("messages", "messaging", t =>
                        {
                            t.HasCheckConstraint("CK_messages_direction", "direction IN (1, 2)");

                            t.HasCheckConstraint("CK_messages_inbound_not_failed", "direction = 2 OR status <> 4");

                            t.HasCheckConstraint("CK_messages_kind", "kind BETWEEN 1 AND 12");

                            t.HasCheckConstraint("CK_messages_status", "status BETWEEN 1 AND 4");
                        });
                });

            modelBuilder.Entity("Modules.Messaging.Infrastructure.Persistence.WebhookDeliveryRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempts");

                    b.Property<byte[]>("BodySha256")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("body_sha256");

                    b.Property<DateTimeOffset?>("ClaimedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_until");

                    b.Property<string>("LastError")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("last_error");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.HasKey("Id");

                    b.HasIndex("BodySha256")
                        .IsUnique()
                        .HasDatabaseName("IX_webhook_deliveries_body_sha256");

                    b.HasIndex("Id")
                        .HasDatabaseName("IX_webhook_deliveries_pending")
                        .HasFilter("processed_at IS NULL");

                    b.ToTable("webhook_deliveries", "messaging");
                });

            modelBuilder.Entity("Modules.Messaging.Infrastructure.Persistence.MessageMediaRecord", b =>
                {
                    b.HasOne("Modules.Messaging.Infrastructure.Persistence.MessageRecord", null)
                        .WithOne("Media")
                        .HasForeignKey("Modules.Messaging.Infrastructure.Persistence.MessageMediaRecord", "MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_message_media_message");
                });

            modelBuilder.Entity("Modules.Messaging.Infrastructure.Persistence.MessageRecord", b =>
                {
                    b.HasOne("Modules.Messaging.Domain.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_messages_conversation");
                });

            modelBuilder.Entity("Modules.Messaging.Infrastructure.Persistence.MessageRecord", b =>
                {
                    b.Navigation("Media");
                });
#pragma warning restore 612, 618
        }
    }
}
